version: '3'
services:
  movies:
    image: durgaprasad49/moviesrepopaytm:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: durgaprasad49/trainrepopaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: durgaprasad49/dthrepopaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: durgaprasad49/rechargerepopaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
